---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app sesame
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      main:
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: RollingUpdate
        containers:
          main:
            image:
              repository: ghcr.io/superquinquin-sur-deule/sesame
              tag: 1.1.0@sha256:1ef0622a1708c3d10244a513a04a3f4e1493d1e88e4200089545a48a2c16ce28

            envFrom:
              - secretRef:
                  name: sesame-secret

            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 1Gi

    service:
      main:
        controller: main
        ports:
          http:
            port: &port 8080

    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Sésame
          gethomepage.dev/group: Magasin
          gethomepage.dev/icon: mdi-key-chain-variant
          gethomepage.dev/description: Gestion des accès
          gethomepage.dev/external: "true"
        hostnames:
          - "sesame.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - name: *app
                port: *port
