---
apiVersion: v1
kind: Secret
metadata:
  name: sesame-secret
stringData:
  ODOO_URL: ENC[AES256_GCM,data:JKFypqgXq4iMajVCqCixfBtMCp+JsW9b5vywAvWDnc0iAUQb,iv:RbqvYxEtyeySsIbh4ddOalig0m9FcuPZq+u+H9pkAdc=,tag:llyujS/nS4kw7MkjbSYBwQ==,type:str]
  ODOO_DATABASE: ENC[AES256_GCM,data:wspEMZYX8oWjMhXcXdvNkggV,iv:ksz9oMNb5poBpy6CAAtZm8Ou0Z1o5fgw62tRB8DXBi0=,tag:VRThFX1AC5tlSskpYveCWA==,type:str]
  ODOO_LOGIN: ENC[AES256_GCM,data:vtKqoTTaklTEdhlnh85SKCxTkWjzVmu2txt+VUhvjzjZvXo=,iv:JaW4terF9Orc2yDd+YfmcpNWUtCWYH7KOTcPtlyw6jg=,tag:Wo73I8QFAGtrs7bMMB9lMg==,type:str]
  ODOO_PASSWORD: ENC[AES256_GCM,data:FPpLcYh/WivAIs7tZjp+Mnf8SW/fr6aqtzpERmcMOeFQPPE=,iv:umWtA85FBuzUX7Owu3mifcmCfR9ulk7hunxorpWSQII=,tag:m8/1AX4BK/m+mqTDSHIG3Q==,type:str]
sops:
  age:
    - recipient: age1hhr8vttgs6yjp8rw3uhjxvtwcjuv0uwgac8llxzkm2ttu7p3augsxf6wpt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dW5uVWo1V0RVUFhjeEF6
        ck5UcUNVcVI2d0l4YTF2MTVDVzFTRkRuNkY0Cmp6NXdCMUJWSWY4MUU5a2VvdWhH
        NHFhTW9GSVNQUm1VTUZJdXFVUnVRSjgKLS0tIHY5UGwwRVBHOWJmRDQ5YzEvZDVD
        UVFlaHQ0c2pDNWg2ZlgwNCswMmtYOTQKVBCK0IEGZtX1MIZpKQ/GlK9QttbDTd8j
        OJwTVrX8AVYZPwJZB41k67BOkovNJuKw1WUZfAvrGE116N3Zl5Am0w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-26T07:31:01Z"
  mac: ENC[AES256_GCM,data:BK7MgPog/V3KOSG5chympu2SHL1Vgxc3QZdfZ+irAic0m1gDwcZR5XqVxdeWS7nVRXUC4jh59MkUozgczACt0RxRPmTp9Ch/Bcy9KY6naCvdsBH9W09EDSedJ4ruPqTAMYVFS6Y3i27CXFIfqWwb8pS0FzzjLqFyzwxGm6mRhQc=,iv:JnY7Do1E7k/Ua8YBgUmJebvCbLjawkhwAbHPOZiLQOU=,tag:zapnM7tMgoCJkwOpkp5mWA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
