---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: routines

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./adjust-ftop-seats/ks.yaml
  - ./reset-ftop-counter/ks.yaml
  - ./sync-odoo-brevo/ks.yaml
