---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/alertmanagerconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
spec:
  route:
    receiver: blackhole
    repeatInterval: 12h
    groupBy:
      - alertname
      - namespace
      - severity
    groupInterval: 5m
    groupWait: 1m
    routes:
      - receiver: rocketchat-hygiene
        repeatInterval: 30m
        matchers:
          - name: team
            value: hygiene-securite
            matchType: =
      - receiver: rocketchat
        matchers:
          - name: severity
            value: critical
            matchType: =
  inhibitRules:
    - equal:
        - alertname
        - namespace
      sourceMatch:
        - name: severity
          value: critical
          matchType: =
      targetMatch:
        - name: severity
          value: warning
          matchType: =
  receivers:
    - name: blackhole
    - name: rocketchat
      slackConfigs:
        - apiURL:
            name: alertmanager-rocketchat
            key: webhook-url
          sendResolved: true
          title: >-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }} {{ .Alerts.Firing | len }}{{ end }}]
            {{ .CommonLabels.alertname }}
          text: >-
            {{ range .Alerts }}*{{ .Annotations.summary }}*

            {{ if .Labels.namespace }}Namespace: `{{ .Labels.namespace }}` · {{ end }}Sévérité: `{{ .Labels.severity }}`

            {{ end }}
    - name: rocketchat-hygiene
      slackConfigs:
        - apiURL:
            name: alertmanager-rocketchat
            key: webhook-url
          channel: "#hygiene-alertes"
          sendResolved: true
          title: >-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }} {{ .Alerts.Firing | len }}{{ end }}]
            {{ .CommonLabels.alertname }}
          text: >-
            {{ range .Alerts }}*{{ .Annotations.summary }}*

            {{ if .Labels.sensor }}Sonde: `{{ .Labels.sensor }}` · {{ end }}Sévérité: `{{ .Labels.severity }}`

            {{ end }}
