---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-operator
spec:
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: grafana-operator
      namespace: observability
  interval: 1h
  path: ./kubernetes/apps/observability/grafana-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: observability
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana-instance
spec:
  dependsOn:
    - name: grafana-operator
    - name: kube-prometheus-stack
    - name: loki
    - name: external-secrets-stores
      namespace: external-secrets
    - name: keycloak-operator
      namespace: auth
  interval: 1h
  path: ./kubernetes/apps/observability/grafana-operator/instance
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: observability
  wait: false
