---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-store
  target:
    name: keycloak-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        KC_DB_URL: '{{ index . "jdbc-uri" }}'
        KC_BOOTSTRAP_ADMIN_USERNAME: kcadmin
        KC_BOOTSTRAP_ADMIN_PASSWORD: '{{ .KC_BOOTSTRAP_ADMIN_PASSWORD }}'
  dataFrom:
    - extract:
        key: auth/keycloak
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: openbao
    - extract:
        key: pg-main-pguser-keycloak
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: pg-main-pguser-store

