---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:mRdgqGRwCTqXtcDVYiM5NRukuUTJJea/Tq5RN52CRMZ+ecnRmwLz66D0/yJC5AUQvzKIA6I=,iv:Dhk0APOMFS/7sDgyWAVoJ9Fl21GpVjJd7S9/I0CtYWE=,tag:jmOfHPOad6f1T9sR8zBV3A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YWpkdEtPWmdMZTE3Sjhn
        NmlyWVRJdmlqTFNkTW9rNTVaaHR1Y09mQXhRCmk1WlVwRmsvNGhQQ2wzemlHT0k2
        VWpPdnk0dU9GUE1wZEFqMzhhaWZGZXcKLS0tIHYrdGZQdmlPREZFeVk5Z1RoalUw
        RFNpd2F0Szc3VS9KanB5dElob1lqSGcKN6l2JrAgaJex+YBKtfvi0zs2IrRwNC2F
        ydG+pI6CPQ8BflbIl53a15z5t5pRH+kVyuYym4mT6i3yqIztuZQe4A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hhr8vttgs6yjp8rw3uhjxvtwcjuv0uwgac8llxzkm2ttu7p3augsxf6wpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-25T21:05:39Z"
  mac: ENC[AES256_GCM,data:2mcEZVReyKa62W5rnVJBdtsrPVhKjgXpvshY0dAiGSd+RSOO0GjUCyS7y338QlchyJCRiR8phIh1rm1eeae+9xPYvuYeJTO3ZRwv+g+2w2gn67WXNRNQnnL2VwITma4kJlZoghqWoWbxFXWqRkeUphye2YEfaV1g5ziZdldklVc=,iv:ImLoIh1qiwMrVY/HCHADMpMwBwxD2QDMwfen1NwNyc4=,tag:Y6LhQ5raEkdAB1bRLFKvBQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
