---
apiVersion: v1
kind: Secret
metadata:
  name: openbao-unseal
type: Opaque
stringData:
  UNSEAL_KEY: ENC[AES256_GCM,data:DKNvv46XnsTwyQBk1LEQIMYLa8hzAxTzh7PvRghR6w==,iv:/6LvjDIFclkUJoPDpC4d2uN1gjD3g5pPQB+myKXOOmM=,tag:ix9dZ2AZOgxOamQapRGdTg==,type:str]
  ROOT_TOKEN: ENC[AES256_GCM,data:nvSo0J1xGcOMYRO/tD8jwtRf28ELCeB2Nr96A/GIug==,iv:2x+571QhE1p0f3Og9m6gXrnIAeb3qGXlcP0yQYHIcak=,tag:kSwibZ1j+XcROU+9V7nWOg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcGV2YUcwMWJ2cUkzSVYy
        SmxIVGwwN21NQjF6V1VJZmxXRk5QUVRHUDA0ClZQOC83RDNVWkFUcHlUOTI4bUxm
        OHhSNWZ1WjFwUGk2ZjU2VWVrdU5uTXcKLS0tIGZpQ3N0c2drekk3eEV6OGZESW41
        OVlpYjNHSHBYZ2M3N0JwT0g2SEhadEEKmnb8KurMV8Ctb2NRKml5TTgAMM1TAlah
        0/pupsLodYU8sXPAMUlJ60THzraw4qiWv1YtlS0NwNTI1mGzw4o7iQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hhr8vttgs6yjp8rw3uhjxvtwcjuv0uwgac8llxzkm2ttu7p3augsxf6wpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-27T11:26:16Z"
  mac: ENC[AES256_GCM,data:D3RPPj6VYeU1hsosuzr0HmL6kb4W5qgLCXeAW6igi1JPeQTrpTI01lFO76I9qbu6fu59YBpteYPv4BuEj4azTBoRcZS8zmW6+aAyQK6FQ/qLokgHwB0Lhzz2OnW31XAw1zOB5zuEBkekgnu1nIwPcHfsLWDSouur2+G1WLi7OpY=,iv:sYfBb3MuaPgFp8xGhEOGrvTIjcNomrxhr7fD3WMcjz8=,tag:UxJ2q9qVeDOoZGgdYRVwMg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
