---
apiVersion: v1
kind: Secret
metadata:
  name: openbao-unseal
type: Opaque
stringData:
  UNSEAL_KEY: ENC[AES256_GCM,data:LHqY/GiWgiafafowUIqdxl8AMISeZaMagGMS4iKhcSALfWw29CGTKxpIgJw2IDoGbzuRQK0JR0LS9btgVEyzWQ==,iv:nyxg5wGNZIZlXVE7Yf/kUp/+YBSIy6P4lpt+Vt1+eDI=,tag:fudMesnB9Lwaqf3q8E09fw==,type:str]
  ROOT_TOKEN: ENC[AES256_GCM,data:ZS/WM808TCUZXfPCTuGOH6WVAgd3GsihtzI=,iv:0DdntlWvnS8KW5jk5dxuOTNh0MWpsW8lyiUmGXK7lAQ=,tag:E/EzZrBVzpBkj3HfhqNWKA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZcGV2YUcwMWJ2cUkzSVYy
        SmxIVGwwN21NQjF6V1VJZmxXRk5QUVRHUDA0ClZQOC83RDNVWkFUcHlUOTI4bUxm
        OHhSNWZ1WjFwUGk2ZjU2VWVrdU5uTXcKLS0tIGZpQ3N0c2drekk3eEV6OGZESW41
        OVlpYjNHSHBYZ2M3N0JwT0g2SEhadEEKmnb8KurMV8Ctb2NRKml5TTgAMM1TAlah
        0/pupsLodYU8sXPAMUlJ60THzraw4qiWv1YtlS0NwNTI1mGzw4o7iQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hhr8vttgs6yjp8rw3uhjxvtwcjuv0uwgac8llxzkm2ttu7p3augsxf6wpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-27T12:33:15Z"
  mac: ENC[AES256_GCM,data:nUvL7Iv2Qf0eVtxp7zqy3ji0H9t8A2PRiMwpJl0YK6+KJuLVvpLdUerVJOCqyD1pG0q/iG4yp7jlLrha7hJ+cQ/o5uq4MXt9cWZ0C+oqO99t+6l13FEQdmzrwptxKfKLPViBQFFbNOzujovBC2H+XgMVRp8mTkE+dsTY/S8JIvs=,iv:Ir5owwfPqMfFwSEDYfkSIYvnIcJLnLj2P3ROdHeeQhw=,tag:tdXR7ZvHV2Jcu77acq6zjA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
