---
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:hxtlzk29kJSm1OoctwYLpFAqXTTX7glIzy0jGn5UAJc7lyeF0d+FzqLorFVyaB9pc1WQ+0xmlPmHSMrknUZ/YQ==,iv:qOT2VByG+ilHjlxaulCVi/hLQvIv6y6Ph7Ubu/ocE4o=,tag:uySrPzyRHOxLAjTDASvGYQ==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:gbzyJiLMW8Z4gQXmi9+HPmzys/M/mQe9WXEFbg==,iv:0JonKT9Jin/SP5yWdsxaOLRi7cv7aIexFaf4NkY+Uiw=,tag:EFG8B+0CNUpDuJ7tP6IH9w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlV0VMYmZ0WlZrUWhwK2Vp
        RXZYaUpab0RwK0xGcUxYb3hvQUNldFZVMm1VCktVSTBpSjBYeUU1YXBPcU5NZHdS
        TE05N3dvTEZxa3R1NS81MlZSelpYZUEKLS0tIEowZXVWQUlNSVYzdStHZlU5TXFF
        MkNxcGo0U1U3b1ZmNWFhcnhUUFVMaEUKUVMbdcxlVvzyqpVbIzDzwowLfBFcsCXd
        t68gI/uynZ2KByBGA2sOJimpFml00I+h3pbvd5e3Lrm9zWebc7GTQA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hhr8vttgs6yjp8rw3uhjxvtwcjuv0uwgac8llxzkm2ttu7p3augsxf6wpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T16:00:45Z"
  mac: ENC[AES256_GCM,data:ICSbeHRd8dE5xK429pGTuWlyAtaO+E0t586/KkOknvmvhhcJpxQpB3XAIrwdEV9+Umr4k8nKI4onsZz5cGZMATEbFPomADg1BDCDz9kb49iX8hf2g9IdhTOVIohLFBTSbvYUK5PqiZ0qgeUDgJ4ufHK5bqwEV7iKGNsPZnDSeNk=,iv:PN9bE46AheFHKYkrpkNKKjvyJOfRd0hm6A35Sa7Juao=,tag:5YAD3KW51Z/P6YRwbJaYag==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
