---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:642qVqeWjJ87FkX3HEDdpd3GTGLf67heW8AY,iv:2BfeWAQn6+ajAWTRCPq6VWxpOFJRgFKU4jD7JjxrJTM=,tag:3VqHxGqoOOYVnB0uIyb+Lw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMmpKT1BMZ0ZMUmNXVStV
        blFPQjNheEZVeUVLeGNmNTlZUXNnVDQzTmlFCk5YWjJqWlI0MnF4L1llMWlUa2JM
        a0N4ZXFWeXN3MytJN3AvWDVzSmlPMlEKLS0tIElNejlGWExmMlhUZWJsZlVIWHBh
        VWlLMDNDTFBhRFloL21vZjVTRVQ5NHcKI9d2MQ3vLmO3MLGCjQ6cKi9NHz9wfGHe
        wwmq1mzmy/pTqXLIwF08szOJesV+cLzFHqKM7uxD+wu3cv0a4bmf/A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hhr8vttgs6yjp8rw3uhjxvtwcjuv0uwgac8llxzkm2ttu7p3augsxf6wpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-25T21:05:39Z"
  mac: ENC[AES256_GCM,data:mIQx4w45eM79BDwX+7EEEh2HwnioWsPYYtjMmxintt3W6wZ5GxjcrD98GfKnQM6aUgKzkA0yMmu0lZcqOXVEVxU3bemB60ByHLe48KKddCesvSSq1qLsg4O0JGoEfI7kh33Ag6wuZqIYE69zVWIrjGfeCHaMZlrjPGx+3zDzPgg=,iv:3F45OP1CYF0XsiJ8Vi6SixIrQ35sQ83f9gev77yB5bc=,tag:iJ7OISGN3tIuaiI1LcXqnA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
