---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:642qVqeWjJ87FkX3HEDdpd3GTGLf67heW8AY,iv:2BfeWAQn6+ajAWTRCPq6VWxpOFJRgFKU4jD7JjxrJTM=,tag:3VqHxGqoOOYVnB0uIyb+Lw==,type:str]
  SQQ_DOMAIN: ENC[AES256_GCM,data:1Bm2PCkfBAEtA5niAIydfg==,iv:a6Taoix+iP+gcuAuIipjVxpVsIYPczSR4A2WMCt0Cxk=,tag:zPmg6LeKzMgd5YSy4dqnLQ==,type:str]
sops:
  age:
    - recipient: age1hhr8vttgs6yjp8rw3uhjxvtwcjuv0uwgac8llxzkm2ttu7p3augsxf6wpt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMmpKT1BMZ0ZMUmNXVStV
        blFPQjNheEZVeUVLeGNmNTlZUXNnVDQzTmlFCk5YWjJqWlI0MnF4L1llMWlUa2JM
        a0N4ZXFWeXN3MytJN3AvWDVzSmlPMlEKLS0tIElNejlGWExmMlhUZWJsZlVIWHBh
        VWlLMDNDTFBhRFloL21vZjVTRVQ5NHcKI9d2MQ3vLmO3MLGCjQ6cKi9NHz9wfGHe
        wwmq1mzmy/pTqXLIwF08szOJesV+cLzFHqKM7uxD+wu3cv0a4bmf/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-06-05T19:52:19Z"
  mac: ENC[AES256_GCM,data:463F83CYxt4P2ZQZsGY0G9D+9FBYwP65styx5DlJz/pjZ95TeM3aD43+hdfLMVgmXv7h9MDt5967zN9OhRKQs2hXmPPyKpOuc+XJJNA7MLa++HxIrw9wPitQMOzhAzUmq0pWoK7Lj4oXXd7ayph2Qf0w4T3YK1ABGo13a+bzM8A=,iv:tnBsZypSvS/4FmeU/ZMO5MMmnG6zH58PXpZ5n1kc0qY=,tag:kustPeK5RKGahvoV+sAO+g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.13.1
