---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mosquitto-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: mosquitto-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MQTT_USERNAME: "{{ .username }}"
        MQTT_PASSWORD: "{{ .password }}"
  dataFrom:
    - extract:
        key: sondes/mqtt
