---
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:/IdrgeVxttNP0N4xEsu/AW0woHRMVeuBz+oPzmNi9k4=,iv:DxjX1cbMqnJu+bQYj1QqbdwWr+kuX9SwNpRwEIbmN7I=,tag:ExuBybCDOtqlH8nEOspHhQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNeTdOQUhjdVNjUlZ1Yng2
        U3RTc0N6TWd3ZGV4dXhKaXhVeUpPNk41SGdvClhtcHZDQVlOK3ZoK3NtZkx0elFG
        ZlI3eUh0VXpVQlFCdnYxanU1KzZnRUEKLS0tIEhpY3hiaUpsazVVUFVwSG5iVXdv
        Vm9yai9lMTJmU2psSVU4NHZkRnBlUHMK/aaUKVe/Vgh+Ny1nwEEpIRHfBqK5m8YH
        nZ4kwKuNPfK2u1yP+W57jcrM+2WnrUj0UDVShO53LhMz8DZy2drgmQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hhr8vttgs6yjp8rw3uhjxvtwcjuv0uwgac8llxzkm2ttu7p3augsxf6wpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-25T21:05:39Z"
  mac: ENC[AES256_GCM,data:rOZIKJoMh4HgOIsrqpjTSwby5UnuIhv1KDY2uiyvmRaK3zGodusCe8baLJaU3y0QYaIU23dnIsYzply0T5EIBE5USBv4BDOrbRdkBnZDENX0vh8ElNyV6Mv/uEJmwMofe9d+7uASV/D6/8t8vzxDGCKI3RGMUhKHqaEB+7BjLII=,iv:fPC5XxusR/ujSoo10ffm76d7Aw/XZcymoyOKXEbQDaw=,tag:jnkxTaREYmpu5zkC7raXag==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
