---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openbao
spec:
  components:
    - ../../../../components/volsync
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: openbao
      namespace: openbao
  interval: 1h
  path: ./kubernetes/apps/openbao/openbao/app
  postBuild:
    substitute:
      APP: openbao
      VOLSYNC_CAPACITY: 10Gi
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: openbao
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openbao-config
spec:
  dependsOn:
    - name: openbao
  interval: 1h
  path: ./kubernetes/apps/openbao/openbao/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: openbao
  wait: false
