---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: odoo-http
spec:
  interval: 30s
  scrapeTimeout: 10s
  module: http_2xx
  prober:
    url: blackbox-exporter:9115
  targets:
    staticConfig:
      static:
        - https://gestion-sdl.${SQQ_DOMAIN}
      labels:
        target: odoo
