---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-odoo
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: keycloak-odoo
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        odoo-url: '{{ .odoo-url }}'
        odoo-database: '{{ .odoo-database }}'
        admin-login: '{{ .admin-login }}'
        admin-password: '{{ .admin-password }}'
  dataFrom:
    - extract:
        key: auth/odoo
