---
apiVersion: v1.edp.epam.com/v1alpha1
kind: ClusterKeycloak
metadata:
  name: surdeule
spec:
  url: http://keycloak.auth.svc.cluster.local:8080
  auth:
    passwordGrant:
      username:
        value: kcadmin
      passwordRef:
        name: keycloak-admin
        key: password
