---
apiVersion: v1.edp.epam.com/v1alpha1
kind: ClusterKeycloakRealm
metadata:
  name: surdeule
spec:
  clusterKeycloakRef: surdeule
  realmName: surdeule
  frontendUrl: "https://auth.${SECRET_DOMAIN}"
  themes:
    loginTheme: surdeule
