---
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealmComponent
metadata:
  name: odoo-user-storage
spec:
  realmRef:
    name: surdeule
    kind: ClusterKeycloakRealm
  name: odoo-user-storage
  providerId: odoo-user-storage
  providerType: org.keycloak.storage.UserStorageProvider
  config:
    enabled:
      - "true"
    cachePolicy:
      - "DEFAULT"
    odoo-url:
      - "$$keycloak-odoo:ODOO_URL"
    odoo-database:
      - "$$keycloak-odoo:ODOO_DATABASE"
    admin-login:
      - "$$keycloak-odoo:ODOO_LOGIN"
    admin-password:
      - "$$keycloak-odoo:ODOO_PASSWORD"
