---
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: grafana
spec:
  realmRef:
    name: surdeule
    kind: ClusterKeycloakRealm
  clientId: grafana
  public: false
  directAccess: false
  secret: $$grafana-secret:GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
  webUrl: https://grafana.${SECRET_DOMAIN}
  redirectUris:
    - https://grafana.${SECRET_DOMAIN}/login/generic_oauth
  webOrigins:
    - https://grafana.${SECRET_DOMAIN}
  protocolMappers:
    - name: realm-roles
      protocol: openid-connect
      protocolMapper: oidc-usermodel-realm-role-mapper
      config:
        multivalued: "true"
        access.token.claim: "true"
        id.token.claim: "true"
        userinfo.token.claim: "true"
        claim.name: roles
        jsonType.label: String
