---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-backup
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: mongodb-backup-nfs
  resources:
    requests:
      storage: 50Gi
