---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
spec:
  endpoints:
    - dnsName: "external.${SECRET_DOMAIN}"
      recordType: CNAME
      targets:
        - "18a4ae70-bdbc-4b42-89c4-cd72bfa10f6b.cfargotunnel.com"
