---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:fOrvI2ElNWvAWqFeqCEqvT024YcGGmo0J7nMkbFTne5rgypFEspeibaCxlguXtygaZjUhbF7pYzKTnHUguObYSF1EELqBv56d5XtAhhJtymnDzpdeqRoIown/Y2h0nJqBDmzyT9AKWqhf8zspZ7KNs/LIzo63aDhrFu2b4G7jYqkgQ7l9H7gvl7pCqlelMVpqF2cn9fCTq4UJV4cDeU8qTZcLkcw6/p9brRK0uj380KvFfWb,iv:5Q0jzzAPpesTLMfUWR4nujC2n3YmNfnd7xadDu3RsrM=,tag:le0rfK9XzHo59f246VgYmA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSTRZMkFrV1MzVWVXZG53
        akdVQmFJUXV6UjFlK0FEclJkaDJoeElzZ0RnCmhzRjVEcjRsbTE1N2dxdnpyQjRW
        N3pSVVFJQ1c3RzRISFdZYnFRek8yN3MKLS0tIGdkK0h1M1VRS2ZKd1pMQVNqK2p0
        Z2Vmb3dUeEM3YWhyTkdUWHFMSVpCZEkKAmgDllzpOXIkXIF7f/30p7vCqrbojxk8
        x71JoFIRC67OvrTGuFgbGcDMFN8H+M17yX61+62VAK2eWPZgKn9b7A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hhr8vttgs6yjp8rw3uhjxvtwcjuv0uwgac8llxzkm2ttu7p3augsxf6wpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-25T21:05:39Z"
  mac: ENC[AES256_GCM,data:ZEo1bFrkIryr5IGrW8BU+hm/Y6Hx4WtndonzRa8lZ56DlwgGcfcUZ0i1Y5Wfv7G9gX70Q0YIPHD0aho1loLd/+HM4f9AVNRWU1TDbXDwsom5l87SmH9rqyE3KK/8xp8dJ/Ea5ibjK30zFtBt9nieCgGxVXQTBiKmT8tmON6Foqs=,iv:0pmvzBlQxWShwLpuVC7Yd11Xe7EJ15QVDpHq6M0X8DY=,tag:frGPV8jxdhjUUIzEAI1MNA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
