---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sqq-sondages
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: sqq-sondages-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SQQ_ADMIN_PASSWORD: "{{ .SQQ_ADMIN_PASSWORD }}"
        QUARKUS_DATASOURCE_USERNAME: "{{ .user }}"
        QUARKUS_DATASOURCE_PASSWORD: "{{ .password }}"
        QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://{{ .host }}:{{ .port }}/{{ .dbname }}"
  dataFrom:
    - extract:
        key: default/sqq-sondages
    - extract:
        key: pg-main-pguser-sondages
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: pg-main-pguser-store
