---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: zigbee2mqtt-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Surchargent mqtt.user / mqtt.password de la config Zigbee2MQTT
        ZIGBEE2MQTT_CONFIG_MQTT_USER: "{{ .username }}"
        ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: "{{ .password }}"
  dataFrom:
    - extract:
        key: sondes/mqtt
