---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app zigbee2mqtt
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controllers:
      zigbee2mqtt:
        # Une seule instance peut piloter le coordinateur.
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/koenkk/zigbee2mqtt
              tag: 2.9.2
            env:
              TZ: Europe/Paris
              ZIGBEE2MQTT_CONFIG_MQTT_SERVER: mqtt://mosquitto:1883
              ZIGBEE2MQTT_CONFIG_SERIAL_PORT: tcp://192.168.7.127:6638
              ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER: ember
              ZIGBEE2MQTT_CONFIG_FRONTEND_ENABLED: "true"
              ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: "8080"
              ZIGBEE2MQTT_CONFIG_HOMEASSISTANT_ENABLED: "false"
              ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: "false"
              ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL: info
            envFrom:
              - secretRef:
                  name: zigbee2mqtt-secret
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8080
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  failureThreshold: 5
              readiness: *probe
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 25m
                memory: 128Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: zigbee2mqtt
        ports:
          http:
            port: &port 8080
    persistence:
      data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ceph-block
        globalMounts:
          - path: /app/data
    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Zigbee2MQTT
          gethomepage.dev/group: Sondes
          gethomepage.dev/icon: zigbee2mqtt.png
          gethomepage.dev/description: Sondes température Zigbee
        hostnames:
          - "zigbee2mqtt.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
