---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sync-odoo-brevo
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: sync-odoo-brevo-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ODOO_URL: "{{ .ODOO_URL }}"
        ODOO_DATABASE: "{{ .ODOO_DATABASE }}"
        ODOO_LOGIN: "{{ .ODOO_LOGIN }}"
        ODOO_PASSWORD: "{{ .ODOO_PASSWORD }}"
        BREVO_API_KEY: "{{ .BREVO_API_KEY }}"
  dataFrom:
    - extract:
        key: common/odoo
    - extract:
        key: common/brevo
