---
apiVersion: v1
kind: Secret
metadata:
  name: odoo-cli-secret
stringData:
  ODOO_URL: ENC[AES256_GCM,data:KZ4yIJtrA0NGxm7wXRAKeoV/QOv0NQghvqlUANzwrfT85jk2,iv:+Yw6V/e+XJpaUaGfH1OoDCvYT8pfmNECRltG+s2WyUQ=,tag:qNBMXAzH/HMgcwxAY3rXcg==,type:str]
  ODOO_DATABASE: ENC[AES256_GCM,data:/ou3groeYBkdkVfR/K7Q1+O9,iv:TRW54lZB9uIbr+vE1c4+2gHaa/Y3+cJD/losxsvgtVI=,tag:SxS+ciuSeC3pJkFdfZSr2A==,type:str]
  ODOO_LOGIN: ENC[AES256_GCM,data:v+pFjgLuLcXfGJC/SXMd59GgJwuiyDXoF6sMBBufYY4dKZRl4adl,iv:T5nAmP9Aneuh9Vx/dKHRZW0A3/zan1FMjelNcpv/fFQ=,tag:8+9LJLzxLslhLn+EKlwReQ==,type:str]
  ODOO_PASSWORD: ENC[AES256_GCM,data:1Ptn0XgpkLt2OOswAof9IlTIg3PCz1AkzMeK1OE+6O/4K9s=,iv:04NYd+TsU5dQt0DGRPfavW7w0tCgfY9K5ECkUrUfYOo=,tag:9438YPjkFgzv8mAcFP8INQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeTRQRHRwR1NQdElxa1R2
        NG5pd2lYcTZ1TndIOWhneUhNZzAyWElmVm1FCkJURWxYOE1WYmMwZUxKWHZwcEI1
        c3NORm9pV0lXbEN4amVHbHkyNmlHMjQKLS0tIFVjRytwQnQ3ZVM2bkhMemhDMTdi
        NkhXNFM4emVQVUsrUzVyUkVoNTNmdDQKSrLSiG5R4XBrE71OMNrnE/J0THNoV5e3
        RfWabhEAv7sw6Zm4aDBHXWUqqFQUw2Ko22DpNw6FI8/vax579wLiGg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hhr8vttgs6yjp8rw3uhjxvtwcjuv0uwgac8llxzkm2ttu7p3augsxf6wpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T21:06:44Z"
  mac: ENC[AES256_GCM,data:EbLZ4sGb6lhurdnsREDp88aDMjMv7SaSYmf6MYMF7k3Pt81CODcwlSyLcCtVNMEB1Wnn158T948+W8lKoUsRRMOkoumDY7jZ6gr6dKWyZGxtKrwTIdEu6p3iXtnHHggcSeoDqTmmGH2C6sMfTFAutf2DqENF1IbS/RjjUzt9ZQI=,iv:iA8Y7wfSzOgQnWa/DHXNziWuw7NDoLrRUzw3djjQxOo=,tag:USKPBeaL8rLnAT26z7kcgw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
