---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rocketchat-mongodb
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: rocketchat-mongodb
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        mongo-uri: "mongodb://rocketchat:{{ .rocketchat_password }}@mongodb-0.mongodb-svc.database.svc.cluster.local:27017,mongodb-1.mongodb-svc.database.svc.cluster.local:27017,mongodb-2.mongodb-svc.database.svc.cluster.local:27017/rocketchat?replicaSet=mongodb&authSource=rocketchat"
  dataFrom:
    - extract:
        key: database/mongodb
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rocketchat-oidc
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: rocketchat-oidc
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: default/rocketchat
