---
apiVersion: v1
kind: Secret
metadata:
  name: odoo-cli-secret
stringData:
  ODOO_URL: ENC[AES256_GCM,data:uHvbVUUOmOhc+rd1M7Srf3OHhVl8G47aYWBrRk6uzR0bTiUk,iv:5pfzW9v0EzidT4pAexnJ5jaipbWTRtKzygnWbUK3hFQ=,tag:7R4eYdS8Ygv3iln9F5RTtA==,type:str]
  ODOO_DATABASE: ENC[AES256_GCM,data:UkwaKFC6uauiC8o3FQH4zyJY,iv:xqdvWyGECVaLNTXGWJ1FMU1LeuRYt4DKeDuiDQ1b9Hk=,tag:Temsb01VVmi6kLDzRdjzWA==,type:str]
  ODOO_LOGIN: ENC[AES256_GCM,data:u0AVMz2tUsDkDV65WlRvekmFn8IAYp70wlMP0DdRZw2bOPFi+SQm,iv:LL9T+7v5cF780SqZVKEwPfZKhB7MpNSJjCsm3675UpU=,tag:0Vszbr/qUju/pXozaCY38A==,type:str]
  ODOO_PASSWORD: ENC[AES256_GCM,data:455yzwbR2yOZSUySp9jJPbHRUvPmp1wrn2Xulo3F3t9p2yA=,iv:xhQWvv1LenrT8BIMWFg0ELVa4gPdgVPo8otfscwjN5o=,tag:aub+NYEaa6F6yVQKyRkjSA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJKzFFQUszMWllaWJXODFr
        YTE2OTVTeVFUWGY3TitoYk9UQUp0TDNwalgwCmxvdlNpaUp4bm56ZTNoS3cxSUd3
        WDdUVXJwbHBrbzNBcVplRkdnN2I3VkUKLS0tIHJIZmgwdkJUVWwzVGJ1bjlUVEU0
        cnZ0d2ZiZ3c2T3ZaVFgyVWpjVEQ3VHMKDuu+nm9keiIppCAzrmgp1pShOzkbjlWh
        XMWuMcFUPVZeSox8sC7dHPizv69BrL4fVjlhGyPdnJ4SxLDokejanA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hhr8vttgs6yjp8rw3uhjxvtwcjuv0uwgac8llxzkm2ttu7p3augsxf6wpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-27T11:06:30Z"
  mac: ENC[AES256_GCM,data:OJloJnpYIjt2sBaibmAjNvFCwTixrW6Xm6wGgD4BlWqLMDWt1mqCVp/pNyqPytU6iunq2NvOYcvwkl0NeaUpUWcRK3OGBgqWzDjNUGP4kKFOUP5oSVCiDzIaxBKA8NKaY+6hKtI9i3xDh0GABsicjWaIPHmko7J7IfmtQz6hmno=,iv:92Ybt292V2ycwOEjhvuYOOqEaaAIoIK+B+zbN2XWzTk=,tag:yTaBM5bhDR5X/8NOd+kuew==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
