---
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:hv3T3j0B/1+FOjm1Ooc+DKd135Ji18Ftha3lWJnoQ9enOWb/1uSXqwaXwDOVN/BrQGH6fWo=,iv:NB4r7N10Z56UMTDjLMiuKgWeJp4iHmVQ3MMZ7LDYwuk=,tag:xssa18IzDKDrtI7DoV+fQw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWmxvVjVKNDNHNXBGRzNt
        MkxiN2poMm5nMVZ5bWxUQUdNS2V0c3RrVW1ZCjY5ZFA1My9qNENFR0J1YmFEZkRk
        emZhZnhnOUlJUzNNUG5HeDB3R041cTQKLS0tIG9UTG95WmtXN1VFNTJNdWExankw
        dVpTWGxaTkwyQ1JDMHNqbVNOMVFTZlEK0mBqZe6piZiTsTyUGprqN6KXQe2zpqkw
        xEhiuCC57UjxWgB7cH7kxIRF0aHptPR6mIs9d59X+Imv1u8ZlsydFw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hhr8vttgs6yjp8rw3uhjxvtwcjuv0uwgac8llxzkm2ttu7p3augsxf6wpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-25T21:05:39Z"
  mac: ENC[AES256_GCM,data:N5laKBE+iAi8cwG+75MUB9WZO6vFUBYX4amPy18T8kO97qJlVppQGnsFWzezVwaGDtTaxHih7i/CtT2HtvNePJc15I98qQ25/XaDiHNVX4X3LInGDVSTK7BNcRz5btq6OkHN6LntUaZQutO2kBbYlDvi41kHQzc0DgjpWGz2l2k=,iv:7HpDRFdxVh/D6206wk5yOBronOicwH8PtS3KkDcVkbM=,tag:n3acj0DTt9B18lJlnT72WQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
