---
apiVersion: v1
kind: Secret
metadata:
  name: volsync-maintenance-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:MuvLDIq6JTd7CjfKQ61xce2QfyVprUQ3UfHQbf5wN35T5IMD8OOQ+4gnj9kMd/9Cz6ZynFtiPc+n9PKUBVFdKA==,iv:fR2iz+BvxSsYVjMhjXtxmwVxi3XYc3xBe4wjtQaw19M=,tag:9QuUlEwcqZ6QIyTDUdN67A==,type:str]
  KOPIA_REPOSITORY: ENC[AES256_GCM,data:8gDBCoExsuDwozPjfw0uuBWhDNEiD4EJ6rJ5ig==,iv:KJ/R/M4ntBDx9sP9EwHrUdpY0Em/UrYHDTA8gi4GVQY=,tag:vQhvzfLL4curMfKhYcQbSQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBd1Ria1lXNmpPZlBVY3Vs
        VDNXRWpJK29CU3JNZGdyL0wxaDZVaXFFVEFZCjBiek1JdDJlNFlSd2pYWERqcEdZ
        TkJ3aWF1a1lNQWFzUG5hU2x5U2xxalkKLS0tIGYvb2poRnlsTW9KU2JLWHVpbGRF
        b2U3bDVXcFdDTkdPSFZlSlFEdWs4MlkKS869yhNQPW4ttoxGF/CmveXZ294gDu8M
        gg0Bp9dYP0TS/eInNj068GcV8z6LiMqyDlHR6IKhDjuyDVHOlQWH/Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hhr8vttgs6yjp8rw3uhjxvtwcjuv0uwgac8llxzkm2ttu7p3augsxf6wpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T16:00:45Z"
  mac: ENC[AES256_GCM,data:rloc1BAo8jFdYh2m3d/QfnzFNDG48QEzZjQh+78RT8nKjlOT/tTj6wEqiaDsAYMsAhoQA5u/Hn2D0QguY5Yud4bS2/D9GfsHt1wyoURzgSuy8Exdn2Nokl68FshKoa4Dl3+uC4VjSgPPfZyGKhU34Rw12dI73t2x4lPIqlxlQ6w=,iv:P148hxkNMKobXsA6QsQ4lmNKptowrn99OQMAWiNF5/g=,tag:kMhWftGbMVaXFirrxcGuLQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
