---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.7.42:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.7.42"
additionalMachineCertSans: *sans

clusterPodNets:
  - "10.42.0.0/16"
clusterSvcNets:
  - "10.43.0.0/16"

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "k8s-0"
    ipAddress: "192.168.7.10"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/4b3cd373a192c8469e859b7a0cfbed3ecc3577c4a2d346a37b0aeff9cd17cdb0
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "a4:bb:6d:7a:39:d5"
        dhcp: false
        addresses:
          - "192.168.7.10/24"
        routes:
          - gateway: "192.168.7.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.7.42"
  - hostname: "k8s-1"
    ipAddress: "192.168.7.11"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/4b3cd373a192c8469e859b7a0cfbed3ecc3577c4a2d346a37b0aeff9cd17cdb0
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "a4:bb:6d:7d:95:17"
        dhcp: false
        addresses:
          - "192.168.7.11/24"
        routes:
          - gateway: "192.168.7.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.7.42"
  - hostname: "k8s-2"
    ipAddress: "192.168.7.12"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/4b3cd373a192c8469e859b7a0cfbed3ecc3577c4a2d346a37b0aeff9cd17cdb0
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "a4:bb:6d:80:e7:94"
        dhcp: false
        addresses:
          - "192.168.7.12/24"
        routes:
          - gateway: "192.168.7.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.7.42"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

