---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-drop
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: immich-drop-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        IMMICH_API_KEY: "{{ .IMMICH_API_KEY }}"
        SESSION_SECRET: "{{ .SESSION_SECRET }}"
  dataFrom:
    - extract:
        key: default/immich-drop
