---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./kube-memory-overcommit.yaml
  - ./blackbox-probe-failed.yaml
  - ./blackbox-probe-slow.yaml
  - ./alertmanager-cluster-failed-to-send-alerts.yaml
