---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sqq-dlc
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: sqq-dlc-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ODOO_URL: "{{ .ODOO_URL }}"
        ODOO_DATABASE: "{{ .ODOO_DATABASE }}"
        ODOO_LOGIN: "{{ .ODOO_LOGIN }}"
        ODOO_PASSWORD: "{{ .ODOO_PASSWORD }}"
        ODOO_BASIC_AUTH_USERNAME: "{{ .ODOO_BASIC_AUTH_USERNAME }}"
        ODOO_BASIC_AUTH_PASSWORD: "{{ .ODOO_BASIC_AUTH_PASSWORD }}"
        QUARKUS_DATASOURCE_USERNAME: "{{ .user }}"
        QUARKUS_DATASOURCE_PASSWORD: "{{ .password }}"
        QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://{{ .host }}:{{ .port }}/{{ .dbname }}"
        QUARKUS_HTTP_CORS_ORIGINS: "https://dlc-staging.${SECRET_DOMAIN}"
  dataFrom:
    - extract:
        key: staging/sqq-dlc
    - extract:
        key: pg-main-pguser-dlcstaging
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: pg-main-pguser-store
