---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app sync-odoo-brevo
spec:
  interval: 1h
  path: ./kubernetes/apps/routines/sync-odoo-brevo/app
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: routines
  wait: false
