---
apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
stringData:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:A94G8O02+K7i6YHIdOhXCaqxp3O4OjkjJjx5yHv6yUSqL8L4WLXiy6tlprHDVbbIzKA0fAJW6p58j/mis17yzA==,iv:ZU04GP2wQNf/Dkxj6epCeqi/Hom7u0J5tc2aNyLW/5g=,tag:uoc9feArkrUFozCcUImu+w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTjNCQkdFKzA0T3NlRWxl
        QnViOXFDd2dXSWd3QWNyRFA4VnRJcjRKTHpNCkVZZTl4UmRJTm1oVzBPcFUveHFl
        c29NNkhteVEyZVZVMVorKzN5bmRZR1UKLS0tIEVnWUcvMENQYlJMTzNaR01XQTdS
        Z1JYWEU1ejdsdGU5TlBDRWdaM3AzS1kKDWVapX523Ae3bwWxEfnbY/r9Ct+0Mt55
        +W3Jl/jEYd9GIP+f9bhNK+xDqxvjfTC3AIB+okracsFSPf2F40uAlQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1hhr8vttgs6yjp8rw3uhjxvtwcjuv0uwgac8llxzkm2ttu7p3augsxf6wpt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T16:00:45Z"
  mac: ENC[AES256_GCM,data:ffP7WP/oMEsJ3RV7gzYDyrKHVfU+znWRvPahCwlXWfG8ODnH6hwwzd8szqMautTB+ueJv9oK1sCHIP/qhC0R7q/MthZPfcAema30lmUbPvP/ECLLeRbxeRZPvDdSSfiA0SmWB/ziHiEK+0iqf2ui/OMpeqhiCXoDuBfoqLCBupI=,iv:CId8vB0A8s/Bzg0MVHNGcxEXd20/EHYUkWjQy7VGL+k=,tag:+fYUU4pkmgKdOcFvct8npA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
