---
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: immich
spec:
  realmRef:
    name: surdeule
    kind: ClusterKeycloakRealm
  clientId: immich
  public: false
  directAccess: false
  secret: $$immich-secret:OIDC_CLIENT_SECRET
  webUrl: https://photos.${SECRET_DOMAIN}
  redirectUris:
    - https://photos.${SECRET_DOMAIN}/auth/login
    - https://photos.${SECRET_DOMAIN}/user-settings
    - app.immich:///oauth-callback
  webOrigins:
    - https://photos.${SECRET_DOMAIN}
