---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helmrepository.yaml
  - helmrelease.yaml
  - externalsecret.yaml
  - httproute.yaml
  - keycloakclient.yaml

commonLabels:
  app.kubernetes.io/name: semaphore
  app.kubernetes.io/instance: semaphore
