---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sondes-rules
spec:
  groups:
    - name: sondes.rules
      rules:
        - alert: CongelateurTemperatureTropElevee
          annotations:
            summary: >-
              La sonde {{ $labels.sensor }} mesure {{ $value | printf "%.1f" }}°C
              (seuil -15°C) depuis plus de 30 minutes.
          expr: min_over_time(temperature{sensor=~"temp_congelateur_.*"}[30m]) > -15
          for: 0m
          labels:
            severity: critical
            team: hygiene-securite
